[build]
  functions = "netlify/functions"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

  [functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "ejs"]

[functions.api]
  node_bundler = "esbuild"
  external_node_modules = ["mongodb", "mongoose", "connect-mongodb-session"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true